### PR TITLE
Cleaned up Mecurial Interaction code

### PR DESCRIPTION
**Pull request by robertu94**
Cleaned up mercurial interaction code, and added tarball target.

### CODE REVIEW

**Comment by ProtractorNinja** [comment]
I ran into some problems while testing this.

- The `tarball` archive build rule ignores the Makefile.

**Comment by ProtractorNinja** [comment]
Oops.

**Comment by ProtractorNinja** [comment]
I merged your PR, with further changes.
- `tarball` rule renamed to `archive`, to keep things generic.
- Dumped the no-changes checking. With `archive` being `.PHONY`, the archive rebuilds itself every time `make handin` is run. This is somewhat against the `Makefile` philosophy, but I like being able to force a new upload every time.
- The "already tracked" warning is avoided via `test`.

**Comment by robertu94** [comment]
Are you sure?  `test -f` just tests if a file exists,  the file will always exist because you create it when you make `archive`, so you will never add the project archive to the mercurial repo.  Further more, `hg push` doesn't force a push without the `-f` flag.  By default it follows `Makefile` style behavior and will not attempt to push a changeset without any new changes, but also returns 1 if it does not push anything which Make will treat as an error and bailout before any changes are made.

**Comment by ProtractorNinja** [comment]
Oops, you're right about `test -f`. I didn't think that part through.

**Comment by ProtractorNinja** [comment]
Right you are. I fixed the already-added test back to your solution, but also moved the archive rule back into the handin rule. I don't see a reason to extract it, honestly.

From my testing, rebuilding the archive always happens, so mercurial is always willing to push an update. Does that not happen with you?

**Pull request closed without merging**
